services:
  app:
    image: cooderl/wewe-rss:latest
    ports:
      - "${APP_PORT:-4000}:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # 数据库连接地址
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:3306/${DB_NAME}?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
      # 服务接口请求授权码
      - AUTH_CODE=${AUTH_CODE}
      # 提取全文内容模式
      - FEED_MODE=${FEED_MODE:-}
      # 定时更新订阅源Cron表达式
      - CRON_EXPRESSION=${CRON_EXPRESSION:-}
      # 服务接口请求限制，每分钟请求次数
      - MAX_REQUEST_PER_MINUTE=${MAX_REQUEST_PER_MINUTE:-}
      # 外网访问时，需设置为服务器的公网 IP 或者域名地址
      - SERVER_ORIGIN_URL=${SERVER_ORIGIN_URL:-}

networks:
  wewe-rss:
